name: CI-NORM

on:
  # workflow_dispatch:
  push:
    branches: main

  pull_request:
    branches: main

jobs:
  norminette:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Norminette
        run: python3 -m pip install -U norminette

      - name: Run Norminette
        run: norminette
